# Generated by Django 5.1.6 on 2025-03-08 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modelsapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
